"use client";
import { useState } from "react";
import { LoaderCircle, MessageSquarePlus, Send } from "lucide-react";
import type { Ticket, TicketMessage } from "@/backend/modules/tickets/repository";
const labels: Record<Ticket["status"], string> = { open:"جدید",in_progress:"در حال بررسی",waiting_for_user:"منتظر پاسخ شما",answered:"پاسخ داده شده",closed:"بسته" };
export function TicketCenter({ initial }: { initial: Ticket[] }) { const [tickets,setTickets]=useState(initial); const [selected,setSelected]=useState<Ticket|null>(null); const [messages,setMessages]=useState<TicketMessage[]>([]); const [subject,setSubject]=useState(""); const [category,setCategory]=useState("technical"); const [text,setText]=useState(""); const [reply,setReply]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); async function open(ticket:Ticket){setSelected(ticket);const r=await fetch(`/api/tickets/${ticket.ticket_number}`);const d=await r.json();if(r.ok)setMessages(d.messages);}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,category,message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(`تیکت شما با موفقیت ثبت شد ✓ #${d.ticketNumber}`);setSubject("");setText("");const list=await fetch("/api/tickets");setTickets(await list.json());}catch(e){setNotice(e instanceof Error?e.message:"ارسال پیام انجام نشد. دوباره تلاش کنید.");}finally{setBusy(false)}}
 async function sendReply(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);try{const r=await fetch(`/api/tickets/${selected.ticket_number}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:reply})});if(!r.ok)throw new Error();setReply("");await open(selected);}catch{setNotice("ارسال پیام انجام نشد. دوباره تلاش کنید.");}finally{setBusy(false)}}
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><h1 className="text-3xl font-black">تیکت‌های من</h1><p className="mt-2 text-sm text-black/60 dark:text-white/60">پاسخ پشتیبانی و ادامهٔ گفت‌وگو را از همین بخش پیگیری کنید.</p><div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={submit} className="surface rounded-[1.75rem] p-5"><div className="flex items-center gap-2 font-black"><MessageSquarePlus size={19}/> ثبت تیکت جدید</div><input required value={subject} onChange={e=>setSubject(e.target.value)} className="input mt-5" placeholder="موضوع تیکت"/><select value={category} onChange={e=>setCategory(e.target.value)} className="input mt-3"><option value="technical">مشکل فنی</option><option value="payment">خرید و پرداخت</option><option value="account">حساب کاربری</option><option value="feedback">پیشنهاد و انتقاد</option><option value="other">سایر</option></select><textarea required value={text} onChange={e=>setText(e.target.value)} className="input mt-3 min-h-32 py-3" placeholder="پیام خود را بنویسید..."/>{notice?<p role="status" className="mt-3 text-xs text-violet">{notice}</p>:null}<button disabled={busy} className="button-primary mt-4 w-full">{busy?<LoaderCircle className="animate-spin" size={17}/>:<Send size={17}/>} ثبت تیکت</button></form><section className="surface overflow-hidden rounded-[1.75rem]">{tickets.length?tickets.map(t=><button key={t.id} onClick={()=>open(t)} className="block w-full border-b border-black/5 p-4 text-right last:border-0 hover:bg-violet/5 dark:border-white/10"><div className="flex justify-between gap-3"><b>{t.subject}</b><span className="text-xs text-violet">{labels[t.status]}</span></div><p className="mt-1 text-xs text-black/55 dark:text-white/55">#{t.ticket_number} · {t.category}</p></button>):<p className="p-12 text-center text-sm text-black/60 dark:text-white/60">هنوز تیکتی ثبت نشده است.</p>}</section></div>{selected?<section className="surface mt-6 rounded-[1.75rem] p-5"><div className="flex justify-between gap-3"><div><b>{selected.subject}</b><p className="mt-1 text-xs text-black/55">#{selected.ticket_number}</p></div><button onClick={()=>setSelected(null)} className="text-sm text-violet">بستن</button></div><div className="mt-5 grid gap-3">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${m.sender_type==="USER"?"mr-auto bg-violet text-white":"ml-auto bg-black/5 dark:bg-white/10"}`}><p>{m.message}</p><time className="mt-2 block text-[10px] opacity-65">{new Intl.DateTimeFormat("fa-IR",{dateStyle:"short",timeStyle:"short"}).format(new Date(m.created_at))}</time></div>)}</div><form onSubmit={sendReply} className="mt-5 flex gap-2"><input value={reply} onChange={e=>setReply(e.target.value)} className="input" placeholder="پاسخ خود را بنویسید..."/><button disabled={busy} className="button-primary shrink-0 px-4">ارسال</button></form></section>:null}</main> }
