"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { CheckCircle2, Clock3, CreditCard, LogOut, MessageSquareText, PackageCheck, ShieldCheck, Sparkles } from "lucide-react";
import type { AccountOrder, OrderStatus } from "@/backend/modules/orders/repository";
import type { Ticket } from "@/backend/modules/tickets/repository";
import { formatToman } from "@/lib/accounts";

const statusLabel: Record<OrderStatus, string> = { pending: "در انتظار بررسی", approved: "تأیید شده", rejected: "رد شده" };
const statusStyle: Record<OrderStatus, string> = { pending: "bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-200", approved: "bg-green-100 text-green-800 dark:bg-green-400/15 dark:text-green-200", rejected: "bg-red-100 text-red-800 dark:bg-red-400/15 dark:text-red-200" };
type Props = { name: string; phone: string; orders: AccountOrder[]; tickets: Ticket[] };

export function UserDashboard({ name, phone, orders, tickets }: Props) {
  const router = useRouter();
  const pending = orders.filter((order) => order.status === "pending").length;
  const approved = orders.filter((order) => order.status === "approved").length;
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/"); router.refresh(); }

  return <main className="mx-auto max-w-6xl px-4 pb-32 pt-8 sm:px-6 sm:pt-12 lg:px-8">
    <section className="surface relative overflow-hidden rounded-[1.75rem] p-5 sm:rounded-[2.25rem] sm:p-8"><div aria-hidden="true" className="absolute -left-20 -top-24 size-56 rounded-full bg-violet/20 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><span className="eyebrow mb-3">MY ALIPROMPT</span><h1 className="text-3xl font-black tracking-tight sm:text-4xl">سلام {name} ✨</h1><p className="mt-3 text-sm leading-7 text-black/65 dark:text-white/65">مدیریت حساب، سفارش‌های اکانت و دسترسی سریع به کتابخانهٔ پرامپت‌ها.</p><p dir="ltr" className="mt-3 text-sm font-bold text-violet">{phone}</p></div><button type="button" onClick={logout} className="button-ghost h-11 shrink-0 px-4 text-xs"><LogOut aria-hidden="true" size={16} /> خروج از حساب</button></div></section>
    <section aria-label="خلاصهٔ حساب" className="mt-6 grid gap-3 min-[480px]:grid-cols-3 sm:gap-4"><Stat icon={<PackageCheck aria-hidden="true" size={20} />} label="همهٔ سفارش‌ها" value={orders.length} tone="violet" /><Stat icon={<Clock3 aria-hidden="true" size={20} />} label="در انتظار بررسی" value={pending} tone="amber" /><Stat icon={<CheckCircle2 aria-hidden="true" size={20} />} label="تأیید شده" value={approved} tone="green" /></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="surface rounded-[1.75rem] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="eyebrow">ACCOUNT ORDERS</span><h2 className="mt-1 text-2xl font-black">سفارش‌های من</h2></div><Link href="/accounts?plan=all-accounts" className="button-accent h-10 px-4 text-xs"><CreditCard aria-hidden="true" size={16} /> خرید اکانت</Link></div>{orders.length ? <div className="mt-5 divide-y divide-black/5 dark:divide-white/10">{orders.map((order) => <article key={order.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-black">{order.plan_title}</h3><p className="mt-1 text-xs text-black/55 dark:text-white/55">شماره پیگیری: <span dir="ltr">{order.reference}</span></p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${statusStyle[order.status]}`}>{statusLabel[order.status]}</span></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-black/60 dark:text-white/60"><span>{formatToman(order.amount)} تومان</span><time>{new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium" }).format(new Date(order.created_at))}</time></div>{order.admin_note ? <p className="mt-3 rounded-xl bg-black/5 px-3 py-2 text-xs leading-6 dark:bg-white/10">یادداشت پشتیبانی: {order.admin_note}</p> : null}</article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-black/15 px-4 py-10 text-center dark:border-white/15"><PackageCheck aria-hidden="true" size={28} className="mx-auto text-violet" /><p className="mt-3 font-black">هنوز سفارشی ثبت نشده است.</p><p className="mt-1 text-xs leading-6 text-black/60 dark:text-white/60">پس از خرید و ارسال رسید، وضعیت سفارش اینجا نمایش داده می‌شود.</p></div>}</div>
      <aside className="grid gap-4"><Link href="/tickets" className="depth-tile surface rounded-[1.75rem] p-5"><span className="grid size-11 place-items-center rounded-2xl bg-violet text-white"><MessageSquareText aria-hidden="true" size={21} /></span><h2 className="mt-4 text-xl font-black">تیکت‌های من {tickets.some((ticket) => ticket.unread_for_user) ? <span className="rounded-full bg-acid px-2 py-0.5 text-xs text-ink">{tickets.filter((ticket) => ticket.unread_for_user).length}</span> : null}</h2><p className="mt-2 text-sm leading-6 text-black/65 dark:text-white/65">پیام‌های پشتیبانی و ادامهٔ گفت‌وگو را اینجا پیگیری کن.</p></Link><Link href="/#prompts" className="depth-tile surface rounded-[1.75rem] p-5"><span className="grid size-11 place-items-center rounded-2xl bg-violet text-white"><Sparkles aria-hidden="true" size={21} /></span><h2 className="mt-4 text-xl font-black">کتابخانهٔ پرامپت‌ها</h2><p className="mt-2 text-sm leading-6 text-black/65 dark:text-white/65">پرامپت آماده را انتخاب کن و با یک کلیک کپی کن.</p></Link><Link href="/accounts?plan=all-accounts" className="depth-tile surface rounded-[1.75rem] p-5"><span className="grid size-11 place-items-center rounded-2xl bg-acid text-ink"><CreditCard aria-hidden="true" size={21} /></span><h2 className="mt-4 text-xl font-black">خرید اکانت</h2><p className="mt-2 text-sm leading-6 text-black/65 dark:text-white/65">سرویس را انتخاب کن، رسید پرداخت را بفرست و از همین پنل پیگیری کن.</p></Link><div className="rounded-[1.75rem] bg-ink p-5 text-white"><ShieldCheck aria-hidden="true" size={22} className="text-acid" /><h2 className="mt-3 font-black">حساب امن</h2><p className="mt-1 text-xs leading-6 text-white/70">اطلاعات ورود و رسیدهای پرداخت فقط برای پردازش سفارش استفاده می‌شوند.</p></div></aside>
    </section>
  </main>;
}

function Stat({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: number; tone: "violet" | "amber" | "green" }) {
  const styles = { violet: "bg-violet/10 text-violet", amber: "bg-amber-500/10 text-amber-700 dark:text-amber-300", green: "bg-green-500/10 text-green-700 dark:text-green-300" };
  return <div className="surface flex min-w-0 items-center gap-3 rounded-2xl p-4"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${styles[tone]}`}>{icon}</span><div className="min-w-0"><span className="block truncate text-xs text-black/60 dark:text-white/60">{label}</span><b className="text-2xl font-black">{value}</b></div></div>;
}
