CREATE DATABASE IF NOT EXISTS aliprompt CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aliprompt;
CREATE TABLE IF NOT EXISTS admins (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,phone VARCHAR(20) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS prompts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(160) NOT NULL,slug VARCHAR(180) NOT NULL UNIQUE,description TEXT NOT NULL,prompt_text MEDIUMTEXT NOT NULL,category VARCHAR(80) NOT NULL,tags JSON NOT NULL,image VARCHAR(500) NOT NULL,status ENUM('published','draft') NOT NULL DEFAULT 'draft',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_status_created(status,created_at),INDEX idx_category(category),FULLTEXT INDEX idx_prompt_search(title,description)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS prompt_ratings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,prompt_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT chk_prompt_rating CHECK (rating BETWEEN 1 AND 5),CONSTRAINT fk_prompt_ratings_prompt FOREIGN KEY(prompt_id) REFERENCES prompts(id) ON DELETE CASCADE,CONSTRAINT fk_prompt_ratings_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,UNIQUE KEY uq_prompt_ratings_user(prompt_id,user_id),INDEX idx_prompt_ratings_prompt(prompt_id),INDEX idx_prompt_ratings_user(user_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tickets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_number VARCHAR(32) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL,subject VARCHAR(180) NOT NULL,category VARCHAR(40) NOT NULL,status ENUM('open','in_progress','waiting_for_user','answered','closed') NOT NULL DEFAULT 'open',priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,last_message_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at TIMESTAMP NULL,FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_tickets_user_last(user_id,last_message_at),INDEX idx_tickets_status_last(status,last_message_at),INDEX idx_tickets_priority_last(priority,last_message_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ticket_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,sender_type ENUM('USER','ADMIN') NOT NULL,message TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,read_at TIMESTAMP NULL,FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,INDEX idx_ticket_messages_ticket_created(ticket_id,created_at),INDEX idx_ticket_messages_unread(ticket_id,sender_type,read_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS account_orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,plan_slug VARCHAR(80) NOT NULL,plan_title VARCHAR(160) NOT NULL,amount INT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'IRT',activation_email VARCHAR(190) NULL,contact_phone VARCHAR(20) NULL,activation_password_ciphertext TEXT NULL,activation_password_iv VARCHAR(64) NULL,activation_password_tag VARCHAR(64) NULL,reference VARCHAR(100) NOT NULL,receipt_name VARCHAR(180) NOT NULL,receipt_type VARCHAR(80) NOT NULL,receipt MEDIUMBLOB NOT NULL,status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',admin_note VARCHAR(500) NULL,reviewed_by BIGINT UNSIGNED NULL,reviewed_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_account_orders_status(status,created_at),INDEX idx_account_orders_user(user_id,created_at)) ENGINE=InnoDB;
