"use client";

import { CheckCircle2, ChevronDown, ExternalLink, Eye, EyeOff, FileText, LoaderCircle, Search, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import type { AccountOrder, OrderStatus } from "@/backend/modules/orders/repository";
import { formatToman } from "@/lib/accounts";

const statusLabel: Record<OrderStatus, string> = { pending: "در انتظار بررسی", approved: "تأییدشده", rejected: "ردشده" };
const statusStyle: Record<OrderStatus, string> = { pending: "bg-amber-100 text-amber-800 dark:bg-amber-400/15 dark:text-amber-200", approved: "bg-green-100 text-green-800 dark:bg-green-400/15 dark:text-green-200", rejected: "bg-red-100 text-red-800 dark:bg-red-400/15 dark:text-red-200" };
type Credentials = { email: string | null; phone: string | null; password: string | null };

export function AdminOrders({ initial }: { initial: AccountOrder[] }) {
  const [orders, setOrders] = useState(initial);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | OrderStatus>("all");
  const [busyId, setBusyId] = useState("");
  const [note, setNote] = useState<Record<string, string>>({});
  const [expandedId, setExpandedId] = useState("");
  const [credentials, setCredentials] = useState<Record<string, Credentials>>({});
  const [credentialsBusy, setCredentialsBusy] = useState("");
  const [credentialsError, setCredentialsError] = useState<Record<string, string>>({});
  const filtered = useMemo(() => orders.filter((order) => `${order.plan_title} ${order.user_name} ${order.user_phone} ${order.reference}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (status === "all" || order.status === status)), [orders, query, status]);
  const pending = orders.filter((order) => order.status === "pending").length;

  async function review(order: AccountOrder, nextStatus: OrderStatus) {
    setBusyId(order.id);
    try { const response = await fetch(`/api/admin/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus, note: note[order.id] ?? order.admin_note ?? "" }) }); if (!response.ok) throw new Error("ذخیرهٔ وضعیت انجام نشد."); setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status: nextStatus, admin_note: note[order.id] ?? item.admin_note, reviewed_at: new Date().toISOString() } : item)); } finally { setBusyId(""); }
  }

  async function revealCredentials(id: string) {
    setCredentialsBusy(id); setCredentialsError((current) => ({ ...current, [id]: "" }));
    try { const response = await fetch(`/api/admin/orders/${id}/credentials`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "دریافت اطلاعات فعال‌سازی انجام نشد."); setCredentials((current) => ({ ...current, [id]: body })); } catch (error) { setCredentialsError((current) => ({ ...current, [id]: error instanceof Error ? error.message : "خطا در دریافت اطلاعات" })); } finally { setCredentialsBusy(""); }
  }

  return <section className="mt-8" aria-labelledby="orders-title"><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><span className="eyebrow">ACCOUNT ORDERS</span><h2 id="orders-title" className="mt-1 text-2xl font-black sm:text-3xl">سفارش‌های اکانت</h2><p className="mt-1 text-xs text-black/60 dark:text-white/60">{pending} سفارش در انتظار بررسی</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-black text-amber-800 dark:bg-amber-400/15 dark:text-amber-200">{orders.length} سفارش</span></div>
    <div className="surface rounded-[1.5rem] p-4 sm:rounded-[1.75rem] sm:p-5"><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><label className="relative"><Search aria-hidden="true" size={17} className="absolute right-4 top-1/2 -translate-y-1/2 text-black/45 dark:text-white/45" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="control pr-11" placeholder="نام، شماره، سرویس یا شماره پیگیری..." /></label><select value={status} onChange={(event) => setStatus(event.target.value as "all" | OrderStatus)} className="input" aria-label="فیلتر وضعیت سفارش"><option value="all">همهٔ وضعیت‌ها</option><option value="pending">در انتظار بررسی</option><option value="approved">تأییدشده</option><option value="rejected">ردشده</option></select></div></div>
    <div className="surface mt-4 overflow-hidden rounded-[1.5rem] sm:rounded-[1.75rem]">{filtered.length ? filtered.map((order) => { const isOpen = expandedId === order.id; const detail = credentials[order.id]; return <article key={order.id} className="border-b border-black/5 p-4 last:border-0 sm:p-5 dark:border-white/5"><div className="flex flex-col justify-between gap-3 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><b>{order.plan_title}</b><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyle[order.status]}`}>{statusLabel[order.status]}</span><span className="text-xs text-black/55 dark:text-white/55">#{order.id}</span></div><p className="mt-2 text-sm font-bold">{order.user_name} <span dir="ltr" className="font-medium text-black/60 dark:text-white/60">{order.user_phone}</span></p><p className="mt-1 text-xs text-black/60 dark:text-white/60">مبلغ: {formatToman(order.amount)} تومان · پیگیری: <span dir="ltr">{order.reference}</span></p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setExpandedId(isOpen ? "" : order.id)} className="button-ghost h-10 px-4 text-xs" aria-expanded={isOpen}>جزئیات کامل <ChevronDown aria-hidden="true" size={16} className={isOpen ? "rotate-180 transition" : "transition"} /></button><a href={`/api/admin/orders/${order.id}/receipt`} target="_blank" rel="noreferrer" className="button-ghost h-10 px-4 text-xs"><FileText aria-hidden="true" size={16} /> رسید <ExternalLink aria-hidden="true" size={14} /></a></div></div>
      {isOpen && <div className="mt-5 rounded-2xl border border-violet/20 bg-violet/[.035] p-4 sm:p-5"><h3 className="font-black">اطلاعات کامل سفارش</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="نام حساب کاربری" value={order.user_name} /><Info label="شماره ثبت‌نام" value={order.user_phone} ltr /><Info label="ایمیل فعال‌سازی" value={order.activation_email || "برای سفارش‌های قدیمی ثبت نشده"} ltr={Boolean(order.activation_email)} /><Info label="شماره پاسخ‌گو" value={order.contact_phone || "برای سفارش‌های قدیمی ثبت نشده"} ltr={Boolean(order.contact_phone)} /><Info label="سرویس" value={order.plan_title} /><Info label="مبلغ نهایی" value={`${formatToman(order.amount)} تومان`} /><Info label="شماره پیگیری" value={order.reference} ltr /><Info label="فایل رسید" value={order.receipt_name} /></dl><div className="mt-5 rounded-xl bg-black/[.045] p-4 dark:bg-white/[.07]"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-black/55 dark:text-white/55">رمز عبور</p><p dir="ltr" className="mt-1 font-mono text-sm">{detail ? (detail.password || "برای سفارش‌های قدیمی ثبت نشده") : "برای مشاهده روی دکمه بزنید"}</p></div>{detail ? <button type="button" onClick={() => setCredentials((current) => { const next = { ...current }; delete next[order.id]; return next; })} className="button-ghost h-10 px-3 text-xs"><EyeOff aria-hidden="true" size={16} />مخفی‌کردن</button> : <button type="button" onClick={() => revealCredentials(order.id)} disabled={credentialsBusy === order.id} className="button-ghost h-10 px-3 text-xs">{credentialsBusy === order.id ? <LoaderCircle aria-hidden="true" size={16} className="animate-spin" /> : <Eye aria-hidden="true" size={16} />}نمایش رمز</button>}</div>{credentialsError[order.id] ? <p role="alert" className="mt-3 text-xs text-red-600 dark:text-red-300">{credentialsError[order.id]}</p> : null}</div></div>}
      <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto]"><input value={note[order.id] ?? order.admin_note ?? ""} onChange={(event) => setNote({ ...note, [order.id]: event.target.value })} className="input" maxLength={500} placeholder="یادداشت مدیر (اختیاری)" /><div className="flex gap-2"><button disabled={busyId === order.id} onClick={() => review(order, "approved")} className="button h-11 bg-green-600 px-4 text-xs text-white hover:-translate-y-0.5"><CheckCircle2 aria-hidden="true" size={16} />تأیید</button><button disabled={busyId === order.id} onClick={() => review(order, "rejected")} className="button h-11 bg-red-600 px-4 text-xs text-white hover:-translate-y-0.5">{busyId === order.id ? <LoaderCircle aria-hidden="true" className="animate-spin" size={16} /> : <XCircle aria-hidden="true" size={16} />}رد</button></div></div></article>; }) : <div className="px-5 py-16 text-center text-sm text-black/60 dark:text-white/60">سفارشی مطابق این فیلتر پیدا نشد.</div>}</div>
  </section>;
}

function Info({ label, value, ltr = false }: { label: string; value: string; ltr?: boolean }) { return <div className="rounded-xl bg-white/70 p-3 dark:bg-white/5"><dt className="text-[11px] font-bold text-black/50 dark:text-white/50">{label}</dt><dd dir={ltr ? "ltr" : undefined} className="mt-1 break-all font-bold">{value}</dd></div>; }
